#BHMenu config file.
#
#IMPORTANT INFO
#Partner id and Pack id can be found at https://www.bisecthosting.com/partners/console.php
#
#Language translation keys are:
#'server_entry.title' for the config title;
#'server_entry.description' for the config description.
#
#Mon Nov 07 10:09:00 GMT 2022
partner_id=3051
use_language_files=false
pack_id=18334
description=Click Here\: Save 25% with code\: AMPZ
title=Need a server?
